---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Config
      shell: aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster

    - name: Run kubectl
      shell: kubectl run cloudv1 --image=marcompp/cloudv1   

    - name: Expose deployment
      shell: kubectl expose pod/cloudv1 --port=80 --type=LoadBalancer 